sync_inverter_time_str = 'Sync inverter time'
inverter_system_time_does_not_need_sync_threshold_sec = 15
inverter_system_time_need_sync_difference_sec = 120
inverter_system_time_too_big_difference_sec = 900
