# See .env file for additional parameters like BRANCH, etc.
#
# BEFORE START NEED TO CREATE SHARED VOLUME:
# docker volume create deye_shared_volume
# docker run --rm -v deye_shared_volume:/data busybox chmod 1777 /data
#
services:
  deye-web:
    build:
      context: .
      dockerfile: deyeweb/Dockerfile
      target: deyeweb
      args:
        BRANCH: ${APP_BRANCH}
    depends_on:
      - deye-proxy
      - deye-cache
      - deye-back-server
    environment:
      DEYE_MASTER_LOGGER_HOST: ${DEYE_MASTER_LOGGER_PROXY_HOST}
      DEYE_MASTER_LOGGER_SERIAL: ${DEYE_MASTER_LOGGER_SERIAL}

      REMOTE_CACHE_SERVER_URL: ${REMOTE_CACHE_SERVER_URL}

      BACK_SERVER_URL: ${DEYE_WEB_BACK_SERVER_URL}

      DEYE_PV_ENERGY_COSTS_JSON: ${DEYE_PV_ENERGY_COSTS_JSON}
      DEYE_GRID_PURCHASED_ENERGY_COSTS_JSON: ${DEYE_GRID_PURCHASED_ENERGY_COSTS_JSON}
      DEYE_GRID_FEED_IN_ENERGY_COSTS_JSON: ${DEYE_GRID_FEED_IN_ENERGY_COSTS_JSON}

      DEYE_ENERGY_COST_CURRENCY_CODE: ${DEYE_ENERGY_COST_CURRENCY_CODE}

      DEYE_GPS_LATITUDE: ${DEYE_GPS_LATITUDE}
      DEYE_GPS_LONGITUDE: ${DEYE_GPS_LONGITUDE}

      DEYE_LOG_NAME: deye-web
    image: deye-web
    container_name: deye-web
    hostname: deye-web
    restart: unless-stopped
    deploy:
      resources:
        limits:
          pids: ${GLOBAL_PIDS_LIMIT}
          memory: ${GLOBAL_MEMORY_LIMIT}
    volumes:
      # Mount shared folder with read-write permissions
      - deye_shared_volume:/var/www/html/data

  deye-back-server:
    build:
      context: .
      dockerfile: deyeweb/Dockerfile
      target: deyebackserver
      args:
        BRANCH: ${APP_BRANCH}
    depends_on:
      - deye-proxy
      - deye-cache
    environment:
      DEYE_MASTER_LOGGER_HOST: ${DEYE_MASTER_LOGGER_PROXY_HOST}
      DEYE_MASTER_LOGGER_SERIAL: ${DEYE_MASTER_LOGGER_SERIAL}

      REMOTE_CACHE_SERVER_URL: ${REMOTE_CACHE_SERVER_URL}

      DEYE_PV_ENERGY_COSTS_JSON: ${DEYE_PV_ENERGY_COSTS_JSON}
      DEYE_GRID_PURCHASED_ENERGY_COSTS_JSON: ${DEYE_GRID_PURCHASED_ENERGY_COSTS_JSON}
      DEYE_GRID_FEED_IN_ENERGY_COSTS_JSON: ${DEYE_GRID_FEED_IN_ENERGY_COSTS_JSON}

      DEYE_ENERGY_COST_CURRENCY_CODE: ${DEYE_ENERGY_COST_CURRENCY_CODE}

      DEYE_GPS_LATITUDE: ${DEYE_GPS_LATITUDE}
      DEYE_GPS_LONGITUDE: ${DEYE_GPS_LONGITUDE}

      DEYE_LOG_NAME: deye-back-server

      SERVER_PORT: 80
      BACK_EXECUTION_TIMEOUT: 15
    image: deye-back-server
    container_name: deye-back-server
    hostname: deye-back-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          pids: ${GLOBAL_PIDS_LIMIT}
          memory: ${GLOBAL_MEMORY_LIMIT}
    healthcheck:
      test: ["CMD", "/usr/local/bin/pids_guard.sh"]
      interval: 5m
      timeout: 15s
      retries: 1
    volumes:
      # Mount shared folder with read-write permissions
      - deye_shared_volume:/home/backserver/my-deye-scripts/deyeweb/data

  telebot:
    build:
      context: .
      dockerfile: telebot/Dockerfile
      args:
        BRANCH: ${APP_BRANCH}
    depends_on:
      - deye-proxy
      - deye-cache
    environment:
      DEYE_MASTER_LOGGER_HOST: ${DEYE_MASTER_LOGGER_PROXY_HOST}
      DEYE_MASTER_LOGGER_SERIAL: ${DEYE_MASTER_LOGGER_SERIAL}

      REMOTE_CACHE_SERVER_URL: ${REMOTE_CACHE_SERVER_URL}

      DEYE_PV_ENERGY_COSTS_JSON: ${DEYE_PV_ENERGY_COSTS_JSON}
      DEYE_GRID_PURCHASED_ENERGY_COSTS_JSON: ${DEYE_GRID_PURCHASED_ENERGY_COSTS_JSON}
      DEYE_GRID_FEED_IN_ENERGY_COSTS_JSON: ${DEYE_GRID_FEED_IN_ENERGY_COSTS_JSON}

      DEYE_ENERGY_COST_CURRENCY_CODE: ${DEYE_ENERGY_COST_CURRENCY_CODE}

      TELEGRAM_BOT_API_TOKEN: ${TELEGRAM_BOT_API_TOKEN}
      TELEGRAM_PRIVATE_CHAT_ID: ${TELEGRAM_PRIVATE_CHAT_ID}
      TELEGRAM_PUBLIC_CHAT_ID: ${TELEGRAM_PUBLIC_CHAT_ID}

      DEYE_LOG_NAME: telebot
    image: telebot
    container_name: telebot
    hostname: telebot
    restart: unless-stopped
    deploy:
      resources:
        limits:
          pids: ${DEYE_TELEBOT_PIDS_LIMIT}
          memory: ${DEYE_TELEBOT_MEMORY_LIMIT}
    healthcheck:
      test: ["CMD", "/usr/local/bin/pids_guard.sh"]
      interval: 5m
      timeout: 15s
      retries: 1
    volumes:
      # Mount shared folder with read-write permissions
      - deye_shared_volume:/home/telebot/my-deye-scripts/telebot/data

  deye-cache:
    build:
      context: .
      dockerfile: deyecache/Dockerfile
    environment:
      DEYE_LOG_NAME: deye-cache
      SERVER_PORT: 80
      MAX_KEYS_COUNT: 32
      MAX_JSON_SIZE: 32768
      MAX_JSON_STORAGE_SIZE: 262144
    image: deye-cache
    container_name: deye-cache
    hostname: deye-cache
    restart: unless-stopped
    deploy:
      resources:
        limits:
          pids: ${GLOBAL_PIDS_LIMIT}
          memory: ${GLOBAL_MEMORY_LIMIT}
    volumes:
      # Mount shared folder with read-write permissions
      - deye_shared_volume:/home/deyecache/deyecache/data

  deye-proxy:
    build:
      context: .
      dockerfile: deyeproxy/Dockerfile
    environment:
      DEYE_LOG_NAME: deye-proxy
      LOGGER_HOST: ${DEYE_MASTER_LOGGER_HOST}
      LOGGER_PORT: 8899
      PROXY_PORT: 8899
      MAX_CONCURRENT_CONNECTIONS: 10
      CONNECT_TIMEOUT: 5
      DATA_TIMEOUT: 10
      LOG_LEVEL: INFO
    image: deye-proxy
    container_name: deye-proxy
    hostname: deye-proxy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          pids: ${GLOBAL_PIDS_LIMIT}
          memory: ${GLOBAL_MEMORY_LIMIT}
    volumes:
      # Mount shared folder with read-write permissions
      - deye_shared_volume:/home/deyeproxy/deyeproxy/data

  log-observer:
    build:
      context: .
      dockerfile: logobserver/Dockerfile
    image: log-observer
    container_name: log-observer
    hostname: log-observer
    restart: unless-stopped
    deploy:
      resources:
        limits:
          pids: ${GLOBAL_PIDS_LIMIT}
          memory: ${GLOBAL_MEMORY_LIMIT}
    volumes:
      # Mount shared folder with read-write permissions
      - deye_shared_volume:/var/www/html

volumes:
  deye_shared_volume:
    external: true
