# See .env file for additional parameters like BRANCH, etc.
services:
  telebot:
    build:
      context: .
      dockerfile: telebot/Dockerfile
      args:
        - BRANCH=${APP_BRANCH}
    image: telebot
    container_name: telebot
    hostname: telebot
    restart: unless-stopped

  deyeweb:
    build:
      context: .
      dockerfile: deyeweb/Dockerfile
      target: deyeweb
      args:
        - BRANCH=${APP_BRANCH}
    environment:
      - BACK_SERVER_URL=http://172.17.17.27/back
      - USE_APACHE_BACK_SERVER_PROXY=false
    image: deyeweb
    container_name: deyeweb
    hostname: deyeweb
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  demoweb:
    build:
      context: .
      dockerfile: deyeweb/Dockerfile
      target: demoweb
      args:
        - BRANCH=${APP_BRANCH}
    environment:
      - BACK_SERVER_URL=http://172.17.17.27/back
      - USE_APACHE_BACK_SERVER_PROXY=false
    image: demoweb
    container_name: demoweb
    hostname: demoweb
    ports:
      - "8080:80"
      - "4430:443"
    restart: unless-stopped

  demoserver:
    build:
      context: .
      dockerfile: demoserver/Dockerfile
      args:
        - BRANCH=${APP_BRANCH}
        - PORTS=5000 5001
    image: demoserver
    container_name: demoserver
    hostname: demoserver
    ports:
      - "5000:5000"
      - "5001:5001"
    restart: unless-stopped

  deyeproxy:
    build:
      context: .
      dockerfile: deyeproxy/Dockerfile
    environment:
      - LOGGER_HOST=192.168.1.101
      - LOGGER_PORT=8899
      - PROXY_PORT=8899
      - MAX_CONCURRENT_CONNECTIONS=10
      - CONNECT_TIMEOUT=5
      - DATA_TIMEOUT=10
      - LOG_LEVEL=INFO
    image: deyeproxy
    container_name: deyeproxy
    hostname: deyeproxy
    ports:
      - "8899:8899"
    restart: unless-stopped

  deyecache:
    build:
      context: .
      dockerfile: deyecache/Dockerfile
    environment:
      - SERVER_PORT=80
      - MAX_KEYS_COUNT=32
      - MAX_JSON_SIZE=32768
      - MAX_JSON_STORAGE_SIZE=262144
    image: deyecache
    container_name: deyecache
    hostname: deyecache
    ports:
      - "80:80"
    restart: unless-stopped

  deyebackserver:
    build:
      context: .
      dockerfile: deyeweb/Dockerfile
      target: deyebackserver
      args:
        - BRANCH=${APP_BRANCH}
    environment:
      - SERVER_PORT=80
    image: deyebackserver
    container_name: deyebackserver
    hostname: deyebackserver
    ports:
      - "80:80"
    restart: unless-stopped
