#!/usr/bin/python3 -u

# The -u option in Python runs the interpreter in unbuffered mode.
# That means:
# stdout and stderr are written immediately (no buffering).
# You don’t have to wait for the buffer to fill or for the program to
# exit before print() outputs appear.
# Equivalent to setting the environment variable PYTHONUNBUFFERED=1.
# This is especially useful when running Python scripts under systemd,
# Docker, or when piping output to journalctl, because you want log
# messages from print() to show up in real time.

import sys

sys.path.append('../modules')
from common_modules import import_dirs

import_dirs(['src', '../deye/src', '../common'])

import telebot
from mytelebot import MyTelebot

from telebot_credentials import BOT_API_TOKEN
from telebot_send_message import send_private_telegram_message
from common_utils import clock_face_two_oclock_emoji

send_private_telegram_message(f'{clock_face_two_oclock_emoji} Starting telebot...')

bot = telebot.TeleBot(BOT_API_TOKEN)
telebot = MyTelebot(bot)
bot.infinity_polling()
