class TelebotCredentials:
  BOT_API_TOKEN = 'YOUR BOT API TOKEN'
  PRIVATE_CHAT_ID = 'YOUR USER ID TO RECEIVE PRIVATE MESSAGES FROM THE BOT'
  PUBLIC_CHAT_ID = 'YOUR USER ID TO RECEIVE PUBLIC MESSAGES FROM THE BOT'
