# WARNING: IF YOU ARE RENAMING THIS FILE, DON'T
# FORGET TO CHANGE NAME ALSO IN:
# Dockerfile

AddDefaultCharset utf-8

<Directory /var/www/html>
    Options +Indexes +FollowSymLinks
    IndexOptions FancyIndexing FoldersFirst VersionSort NameWidth=* DescriptionWidth=* Charset=UTF-8 ShowForbidden
</Directory>

<FilesMatch "\.(log|txt|csv)$">
    # Force plain text with UTF-8
    Header set Content-Type "text/plain; charset=utf-8"
</FilesMatch>

<FilesMatch "\.json$">
    # Force JSON type with UTF-8
    Header set Content-Type "application/json; charset=utf-8"
</FilesMatch>

<FilesMatch "\.(log|txt|json|csv)$">
    # Force compression regardless of MIME type
    SetOutputFilter DEFLATE

    <IfModule mod_headers.c>
        # Disable caching for specific file types
        Header set Cache-Control "no-cache, no-store, must-revalidate"
        Header set Pragma "no-cache"
        Header set Expires 0
    </IfModule>
</FilesMatch>
