<?php

define('PYTHON_CMD', 'python3 -u');
define('PYTHON_PIPE_READ_TIMEOUT_SEC', 7);
define('FRONT_CACHE_MINIMUM_TIME_FOR_RESET_SEC', 5 * 60);
define('FRONT_CACHE_UPDATE_TIME_SEC', 12 * 60 * 60);
define('FRONT_CACHE_UPDATE_EXECUTION_TIMEOUT_SEC', 15);
define('GZIP_ENCODING_THRESHOLD', 1024);
