name: test checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Initialize and update submodules recursively
        run: git submodule update --init --recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Run deye single inverter tests
        run: |
          cp test/single_inverter/deye_single_inverter_test_loggers.py common/deye_loggers.py
          python -u test/single_inverter/deye_single_inverter_test.py

      - name: Run deye multi inverter tests
        run: |
          cp test/multi_inverter/deye_multi_inverter_test_loggers.py common/deye_loggers.py
          python -u test/multi_inverter/deye_multi_inverter_test.py
